<template>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
  <div class="bg-white">
    {{ $store.getters.tribeGet(1) }}
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
  <div class="bg-black">
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> AuthorDescription

  </div>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'IndexPage',
  methods: {
    ...mapActions(['tribeRead', 'articleRead', 'rockstarRead', 'podcastRead', 'videoRead']),
  },
  created () {
    this.tribeRead()
    this.articleRead()
    this.rockstarRead()
    this.podcastRead()
    this.videoRead()
  }
}
</script>

<style lang="scss">
@import "assets/css/variables";

</style>
